[package]
name = "setwaker"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
futures = { version = "0.3.1", default-features = false }
lock_api = "0.3.3"
hashbrown = { version = "0.6.3", optional = true }

[features]
no_std = ["hashbrown"]
